import "./App.css";

function InputForm() {
  return (
    <div className="input-bar">
        <textarea className="textbox"></textarea>
    </div>
  )
}

function Message({ id, datetime, messagetext }) {
  return (
    <div className="message">
      <p>{id}</p>
      <p>{datetime}</p>
      <div className="message_content">
        <p>{messagetext}</p>
      </div>
    </div>
  )
}

export default function App() {
  return (
    <>
      <Message id={"g4Jx8N"} datetime={"2023-04-15 23:34:55"} messagetext={"Ungafafy uggy dumbo lmao *dabs*"} />
      <Message id={"g4Jx8N"} datetime={"2023-04-15 23:34:55"} messagetext={"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. Massa tincidunt dui ut ornare lectus sit amet est. Fermentum et sollicitudin ac orci phasellus. Eget nulla facilisi etiam dignissim diam quis enim. Nisi porta lorem mollis aliquam. Cursus metus aliquam eleifend mi in nulla. Eu tincidunt tortor aliquam nulla. Ullamcorper velit sed ullamcorper morbi tincidunt. Vel pretium lectus quam id. Lectus proin nibh nisl condimentum. Nam libero justo laoreet sit amet cursus sit amet dictum. Eu nisl nunc mi ipsum faucibus vitae. Magna ac placerat vestibulum lectus. Odio facilisis mauris sit amet massa vitae tortor condimentum.\
Dapibus ultrices in iaculis nunc sed augue. Arcu dui vivamus arcu felis bibendum ut. Lectus urna duis convallis convallis. Scelerisque purus semper eget duis. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Sollicitudin tempor id eu nisl nunc mi ipsum. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Quis lectus nulla at volutpat. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. At in tellus integer feugiat scelerisque varius morbi enim. Risus pretium quam vulputate dignissim suspendisse in est. Blandit turpis cursus in hac. Odio euismod lacinia at quis risus. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Ullamcorper malesuada proin libero nunc consequat. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Mauris pharetra et ultrices neque ornare aenean. In hac habitasse platea dictumst quisque sagittis purus. Placerat in egestas erat imperdiet sed.\
Dui vivamus arcu felis bibendum ut tristique et egestas. Aliquet enim tortor at auctor. Elementum facilisis leo vel fringilla est ullamcorper. Et leo duis ut diam quam. Facilisis volutpat est velit egestas dui id ornare arcu. Morbi enim nunc faucibus a pellentesque sit. Eget velit aliquet sagittis id consectetur purus ut faucibus. Lacus vel facilisis volutpat est velit egestas dui id ornare. Cursus turpis massa tincidunt dui. Orci a scelerisque purus semper eget. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Consequat ac felis donec et odio pellentesque diam. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Non consectetur a erat nam at. Vitae turpis massa sed elementum tempus egestas sed. Dictum at tempor commodo ullamcorper a. Aliquam purus sit amet luctus venenatis lectus magna fringilla.\
Bibendum neque egestas congue quisque egestas diam in arcu. Massa tincidunt nunc pulvinar sapien et ligula. Integer eget aliquet nibh praesent tristique magna sit amet. Egestas quis ipsum suspendisse ultrices gravida dictum. Id cursus metus aliquam eleifend mi. Quis imperdiet massa tincidunt nunc pulvinar. Tempor id eu nisl nunc mi ipsum. Cras pulvinar mattis nunc sed blandit. Volutpat blandit aliquam etiam erat velit scelerisque in. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Eu ultrices vitae auctor eu. Risus at ultrices mi tempus imperdiet nulla. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Dui accumsan sit amet nulla. Vel facilisis volutpat est velit egestas. Non sodales neque sodales ut etiam sit. Sit amet purus gravida quis blandit. Commodo elit at imperdiet dui accumsan.\
Nisl suscipit adipiscing bibendum est ultricies. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Id neque aliquam vestibulum morbi blandit. Nunc mattis enim ut tellus elementum sagittis vitae et. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Tortor pretium viverra suspendisse potenti nullam ac tortor. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Mi quis hendrerit dolor magna eget est lorem ipsum. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. In arcu cursus euismod quis viverra nibh cras. Sed sed risus pretium quam vulputate dignissim suspendisse in. Mus mauris vitae ultricies leo integer malesuada. A condimentum vitae sapien pellentesque habitant morbi tristique. Dui vivamus arcu felis bibendum. Accumsan in nisl nisi scelerisque. Ut sem nulla pharetra diam sit amet nisl. Vitae tortor condimentum lacinia quis vel. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Et malesuada fames ac turpis."} />
      <Message id={"g4Jx8N"} datetime={"2023-04-15 23:34:55"} messagetext={"The quick brown fox jumps over the lazy dog"} />
      <Message id={"g4Jx8N"} datetime={"2023-04-15 23:34:55"} messagetext={"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. Massa tincidunt dui ut ornare lectus sit amet est. Fermentum et sollicitudin ac orci phasellus. Eget nulla facilisi etiam dignissim diam quis enim. Nisi porta lorem mollis aliquam. Cursus metus aliquam eleifend mi in nulla. Eu tincidunt tortor aliquam nulla. Ullamcorper velit sed ullamcorper morbi tincidunt. Vel pretium lectus quam id. Lectus proin nibh nisl condimentum. Nam libero justo laoreet sit amet cursus sit amet dictum. Eu nisl nunc mi ipsum faucibus vitae. Magna ac placerat vestibulum lectus. Odio facilisis mauris sit amet massa vitae tortor condimentum.\
Dapibus ultrices in iaculis nunc sed augue. Arcu dui vivamus arcu felis bibendum ut. Lectus urna duis convallis convallis. Scelerisque purus semper eget duis. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Sollicitudin tempor id eu nisl nunc mi ipsum. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Quis lectus nulla at volutpat. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. At in tellus integer feugiat scelerisque varius morbi enim. Risus pretium quam vulputate dignissim suspendisse in est. Blandit turpis cursus in hac. Odio euismod lacinia at quis risus. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Ullamcorper malesuada proin libero nunc consequat. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Mauris pharetra et ultrices neque ornare aenean. In hac habitasse platea dictumst quisque sagittis purus. Placerat in egestas erat imperdiet sed.\
Dui vivamus arcu felis bibendum ut tristique et egestas. Aliquet enim tortor at auctor. Elementum facilisis leo vel fringilla est ullamcorper. Et leo duis ut diam quam. Facilisis volutpat est velit egestas dui id ornare arcu. Morbi enim nunc faucibus a pellentesque sit. Eget velit aliquet sagittis id consectetur purus ut faucibus. Lacus vel facilisis volutpat est velit egestas dui id ornare. Cursus turpis massa tincidunt dui. Orci a scelerisque purus semper eget. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Consequat ac felis donec et odio pellentesque diam. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Non consectetur a erat nam at. Vitae turpis massa sed elementum tempus egestas sed. Dictum at tempor commodo ullamcorper a. Aliquam purus sit amet luctus venenatis lectus magna fringilla.\
Bibendum neque egestas congue quisque egestas diam in arcu. Massa tincidunt nunc pulvinar sapien et ligula. Integer eget aliquet nibh praesent tristique magna sit amet. Egestas quis ipsum suspendisse ultrices gravida dictum. Id cursus metus aliquam eleifend mi. Quis imperdiet massa tincidunt nunc pulvinar. Tempor id eu nisl nunc mi ipsum. Cras pulvinar mattis nunc sed blandit. Volutpat blandit aliquam etiam erat velit scelerisque in. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Eu ultrices vitae auctor eu. Risus at ultrices mi tempus imperdiet nulla. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Dui accumsan sit amet nulla. Vel facilisis volutpat est velit egestas. Non sodales neque sodales ut etiam sit. Sit amet purus gravida quis blandit. Commodo elit at imperdiet dui accumsan.\
Nisl suscipit adipiscing bibendum est ultricies. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Id neque aliquam vestibulum morbi blandit. Nunc mattis enim ut tellus elementum sagittis vitae et. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Tortor pretium viverra suspendisse potenti nullam ac tortor. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Mi quis hendrerit dolor magna eget est lorem ipsum. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. In arcu cursus euismod quis viverra nibh cras. Sed sed risus pretium quam vulputate dignissim suspendisse in. Mus mauris vitae ultricies leo integer malesuada. A condimentum vitae sapien pellentesque habitant morbi tristique. Dui vivamus arcu felis bibendum. Accumsan in nisl nisi scelerisque. Ut sem nulla pharetra diam sit amet nisl. Vitae tortor condimentum lacinia quis vel. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Et malesuada fames ac turpis."} />
    <div className="footer"></div>
    <InputForm />
    </>
  );
}